# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/02689b6e-3b03-40eb-be5f-236ef7b09b06";
      fsType = "btrfs";
      options = [ "subvol=@FlandreScarletNixOS" "noatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/02689b6e-3b03-40eb-be5f-236ef7b09b06";
      fsType = "btrfs";
      options = [ "subvol=@FlandreScarletNixOSHome" "noatime" "discard=async" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5F92-7B22";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/FlanderyConfigurations" =
    { device = "/dev/disk/by-uuid/02689b6e-3b03-40eb-be5f-236ef7b09b06";
      fsType = "btrfs";
      options = [ "subvol=@FlandreScarletNixOSConfig" ];
    };

  fileSystems."/home/Flandre/FlandreGames" =                                                   
    { device = "/dev/disk/by-uuid/02689b6e-3b03-40eb-be5f-236ef7b09b06";                       
      fsType = "btrfs";                                                                        
      options = [ "subvol=@ReimuGames" "noatime" "discard=async" "compress=zstd" ];                                                                                              
    };   
  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
